export const modalStyles = {
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  overflowY: 'auto',
  width: { xs: '90%', sm: '80%'},
  maxHeight: '100vh',
  maxHeight: '100lvh',
  bgcolor: 'background.paper',
  border: '1px solid #000',
  boxShadow: 24,
  borderRadius: '7px',
  p: {xs: 1, md: 2},
}